import './globals.css';

export const metadata = {
  title: 'UPSC Quiz Hub - AI Powered',
  description: 'UPSC preparation quiz generated by Gemini AI.',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 antialiased min-h-screen">
        {children}
      </body>
    </html>
  );
}