'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Header from '@/components/Header';
import { Loader2 } from 'lucide-react';

export default function HomePage() {
  const [usernameInput, setUsernameInput] = useState('');
  const [existingUser, setExistingUser] = useState(null); 
  const [isChecking, setIsChecking] = useState(false);
  const router = useRouter();

  const checkUser = () => {
      const storedUsername = localStorage.getItem('quiz_username');
      setExistingUser(storedUsername);
  };

  useEffect(() => {
    checkUser();
    window.addEventListener('quiz_user_update', checkUser);
    return () => window.removeEventListener('quiz_user_update', checkUser);
  }, []);

  const handleStart = async () => {
    const userToSave = usernameInput.trim();
    if (!userToSave) {
      alert("Username is required!");
      return;
    }
    setIsChecking(true);

    try {
        //save locally immediately so session is active
        localStorage.setItem('quiz_username', userToSave);
        window.dispatchEvent(new Event('quiz_user_update'));

        // check Database if user exists
        const response = await fetch('/api/user/check', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ username: userToSave }),
        });

        const data = await response.json();

        if (data.exists) {
            // case 1: User exists in DB -> Show "Welcome Back" card
            setExistingUser(userToSave); 
            // We dont redirect here, just update state to show the card
        } else {
            // case 2: new User -> Redirect directly to Select Page
            router.push('/select');
        }

    } catch (error) {
        console.error("Login check failed:", error);
        //if API fails
        router.push('/select');
    } finally {
        setIsChecking(false); 
    }
  };

  return (
    <>
      <Header />
      <main className="max-w-7xl mx-auto p-4 md:p-8">
        <div className="grid md:grid-cols-2 gap-8 items-center pt-10 pb-20">
          
          <div className="space-y-6">
            <h1 className="text-5xl md:text-6xl font-extrabold leading-tight text-white">
              Daily Quiz, Daily Learn — <span className="text-yellow-400"> Let's Play Today!</span>
            </h1>
            
            <p className="text-lg text-gray-300 max-w-lg">
              Let's check your **Knowledge** on a specifc **UPSC Subject**. Questions are generated by AI. <br /> Let's learn new and boost your **UPSC preparation**!
            </p>

            {existingUser ? (
                /* welcome Back Card (Shown if user was in LocalStorage or found in DB) */
                <div className="bg-purple-900/50 p-6 rounded-xl border border-purple-700 mt-6 animate-fade-in w-fit">
                    <h2 className="text-2xl font-bold text-white mb-2">Welcome back, {existingUser}!</h2>
                    <p className="text-gray-400 mb-6">Ready to continue your practice?</p>
                    
                    <div>
                        <button 
                            onClick={() => router.push('/select')}
                            className="px-8 py-3 rounded-lg font-bold text-lg bg-yellow-400 text-purple-900 hover:bg-yellow-500 transition shadow-xl w-full sm:w-auto"
                        >
                            Start New Quiz
                        </button>
                    </div>
                </div>
            ) : (
                /* standard login view */
                <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4 pt-4">
                  <input
                    type="text"
                    placeholder="Enter your username..."
                    value={usernameInput}
                    onChange={(e) => setUsernameInput(e.target.value)}
                    disabled={isChecking}
                    className="p-3 w-full sm:w-64 rounded-lg bg-purple-900 border border-purple-700 text-white placeholder-gray-400 focus:ring-2 focus:ring-yellow-400 focus:border-yellow-400 disabled:opacity-50"
                  />
                  <button
                    onClick={handleStart}
                    disabled={isChecking}
                    className="px-6 py-3 rounded-lg font-bold text-lg bg-yellow-400 text-purple-900 hover:bg-yellow-500 transition shadow-xl flex items-center justify-center min-w-35"
                  >
                    {isChecking ? <Loader2 className="animate-spin mr-2" size={20}/> : "Let's Start"}
                  </button>
                </div>
            )}

          </div>

          <div className="hidden md:flex justify-center items-center">
            <div className="w-80 h-80 bg-purple-800/50 rounded-full flex justify-center items-center relative overflow-hidden">
                <div className="text-8xl opacity-30">🏆</div>
                <div className="absolute inset-0 bg-linear-to-br from-transparent via-purple-500/10 to-transparent"></div>
            </div>
          </div>

        </div>
      </main>
    </>
  );
}